# Generated by Django 4.2.29 on 2026-04-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(default='#4F86C6', help_text="Hexkleurcode inclusief #, bv. '#4F86C6'.", max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Inactieve projecten zijn verborgen bij nieuw invoer maar blijven in de geschiedenis.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projecten',
                'ordering': ['name'],
            },
        ),
    ]
