# Generated by Django 4.2.29 on 2026-03-21 09:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('color', models.CharField(default='#4F86C6', help_text="Hexkleurcode inclusief #, bv. '#4F86C6'.", max_length=7)),
                ('is_active', models.BooleanField(default=True, help_text='Inactieve projecten zijn verborgen bij nieuw invoer maar blijven in de geschiedenis.')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projecten',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Aantal minuten besteed aan dit project op deze datum.', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='time_entries', to='projects.project')),
            ],
            options={
                'verbose_name': 'tijdregistratie',
                'verbose_name_plural': 'tijdregistraties',
                'ordering': ['date', 'project__name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rule', 'Automatisch (regel)'), ('manual', 'Handmatig')], default='rule', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='activities.windowactivity')),
                ('time_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_mappings', to='projects.timeentry')),
            ],
            options={
                'verbose_name': 'activiteitskoppeling',
                'verbose_name_plural': 'activiteitskoppelingen',
                'ordering': ['activity__started_at'],
                'unique_together': {('activity', 'time_entry')},
            },
        ),
    ]
