# Generated by Django 4.2.29 on 2026-03-24 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymapping',
            options={'ordering': ['activity__started_at'], 'verbose_name': 'activiteitskoppeling', 'verbose_name_plural': 'activiteitsoppelingen'},
        ),
    ]
