# Generated by Django 4.2.29 on 2026-04-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_remove_uniqueactivity_occurrences_and_more'),
        ('projects', '0005_switch_to_unique_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitymapping',
            options={'ordering': ['unique_activity__block__started_at'], 'verbose_name': 'activiteitskoppeling', 'verbose_name_plural': 'activiteitskoppelingen'},
        ),
        migrations.AlterField(
            model_name='activitymapping',
            name='unique_activity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='activities.uniqueactivity'),
            preserve_default=False,
        ),
    ]
