# Generated by Django 4.2.29 on 2026-03-24 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('dominant_title', models.TextField(help_text='Venstertitel die het langst actief was binnen dit blok.')),
                ('date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField()),
                ('total_seconds', models.PositiveIntegerField()),
                ('activity_count', models.PositiveIntegerField()),
                ('block_minutes', models.PositiveSmallIntegerField(help_text='Tijdvenster in minuten waarbinnen activiteiten zijn samengevoegd.')),
            ],
            options={
                'verbose_name': 'activiteitsblok',
                'verbose_name_plural': 'activiteitsblokken',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_field', models.CharField(choices=[('app_name', 'Applicatienaam (exact, hoofdletterongevoelig)'), ('title_contains', 'Venstertitel bevat tekst (hoofdletterongevoelig)')], max_length=30)),
                ('match_value', models.CharField(help_text='Waarde om op te matchen (hoofdletterongevoelig).', max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lagere waarde = hogere prioriteit. Bij meerdere matchende regels wint de laagste priority-waarde.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'activiteitsregel',
                'verbose_name_plural': 'activiteitsregels',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WindowActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('raw_title', models.TextField(help_text='Originele venstertitel zoals AHK die heeft vastgelegd.')),
                ('app_name', models.CharField(db_index=True, help_text="Geëxtraheerde applicatienaam (deel na het laatste ' - ').", max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('is_noise', models.BooleanField(db_index=True, default=False, help_text='Automatisch True voor Idle, Program Manager, Task Switching, etc. Kan handmatig worden omgezet. Ruisregels zijn verborgen in de UI.')),
            ],
            options={
                'verbose_name': 'vensteractiteit',
                'verbose_name_plural': 'vensteractiviteiten',
                'ordering': ['started_at'],
            },
        ),
    ]
