# Generated by Django 4.2.29 on 2026-04-01 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField()),
                ('total_seconds', models.PositiveIntegerField(help_text='Opgetelde actieve seconden van alle onderliggende WindowActivity-regels.')),
                ('activity_count', models.PositiveIntegerField(help_text='Aantal WindowActivity-regels samengevoegd in dit blok.')),
                ('block_minutes', models.PositiveSmallIntegerField(help_text='Tijdvenster in minuten waarbinnen activiteiten zijn samengevoegd.')),
                ('project', models.ForeignKey(blank=True, help_text='Project waaraan dit blok is toegewezen (handmatig of automatisch via regel).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_blocks', to='projects.project')),
            ],
            options={
                'verbose_name': 'activiteitsblok',
                'verbose_name_plural': 'activiteitsblokken',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='UniqueActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_title', models.TextField(help_text='De venstertitel waarop gegroepeerd is.')),
                ('total_seconds', models.PositiveIntegerField(help_text='Cumulatieve actieve tijd voor deze titel binnen het blok.')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_activities', to='activities.activityblock')),
            ],
            options={
                'verbose_name': 'unieke activiteit',
                'verbose_name_plural': 'unieke activiteiten',
                'ordering': ['-total_seconds'],
            },
        ),
        migrations.CreateModel(
            name='WindowActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('raw_title', models.TextField(help_text='Originele venstertitel zoals AHK die heeft vastgelegd.')),
                ('app_name', models.CharField(db_index=True, help_text="Geëxtraheerde applicatienaam (deel na het laatste ' - ').", max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('is_noise', models.BooleanField(db_index=True, default=False, help_text='Automatisch True voor Idle, Program Manager, Task Switching, etc. Kan handmatig worden omgezet. Ruisregels zijn verborgen in de UI.')),
                ('unique_activity', models.ForeignKey(blank=True, help_text='De UniqueActivity waar deze regel na aggregatie toe behoort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='activities.uniqueactivity')),
            ],
            options={
                'verbose_name': 'vensteractiviteit',
                'verbose_name_plural': 'vensteractiviteiten',
                'ordering': ['started_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_field', models.CharField(choices=[('app_name', 'Applicatienaam (exact, hoofdletterongevoelig)'), ('title_contains', 'Venstertitel bevat tekst (hoofdletterongevoelig)'), ('dominant_activity', 'Dominante activity-titel geschiedenis'), ('recent_project', 'Recent gebruikt project voor deze app')], max_length=30)),
                ('match_value', models.CharField(help_text='Waarde om op te matchen (hoofdletterongevoelig).', max_length=255)),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Lagere waarde = hogere prioriteit. Bij meerdere matchende regels wint de laagste priority-waarde.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='projects.project')),
            ],
            options={
                'verbose_name': 'activiteitsregel',
                'verbose_name_plural': 'activiteitsregels',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BlockProjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp van de toewijzing.')),
                ('assigned_by', models.CharField(choices=[('rule', 'Automatische regel'), ('manual', 'Handmatig door gebruiker')], default='rule', help_text='Hoe de toewijzing tot stand is gekomen.', max_length=20)),
                ('block', models.ForeignKey(help_text='Het ActivityBlock dat aan een project is toegewezen.', on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='activities.activityblock')),
                ('project', models.ForeignKey(help_text='Het project waartoe het block is toegewezen.', on_delete=django.db.models.deletion.CASCADE, related_name='block_assignments', to='projects.project')),
            ],
            options={
                'verbose_name': 'block-project geschiedenis',
                'verbose_name_plural': 'block-project geschiedenissen',
                'ordering': ['-assigned_at'],
                'indexes': [models.Index(fields=['block', '-assigned_at'], name='activities__block_i_09ffd1_idx'), models.Index(fields=['project', '-assigned_at'], name='activities__project_fead3a_idx')],
            },
        ),
    ]
