# Generated by Django 4.2.29 on 2026-03-24 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityrule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='projects.project'),
        ),
        migrations.AddField(
            model_name='activityblock',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='activities.windowactivity'),
        ),
    ]
