# Generated by Django 4.2.29 on 2026-03-24 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='windowactivity',
            options={'ordering': ['started_at'], 'verbose_name': 'vensteractiviteit', 'verbose_name_plural': 'vensteractiviteiten'},
        ),
        migrations.CreateModel(
            name='BlockTitleSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_title', models.TextField()),
                ('total_seconds', models.PositiveIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='title_summaries', to='activities.activityblock')),
            ],
            options={
                'verbose_name': 'titelsamenvating',
                'verbose_name_plural': 'titelsamenvatingen',
                'ordering': ['-total_seconds'],
            },
        ),
    ]
