# Generated by Django 4.2.29 on 2026-03-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='windowactivity',
            unique_together={('started_at', 'raw_title')},
        ),
    ]
