# Generated by Django 4.2.29 on 2026-03-24 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_alter_windowactivity_options_blocktitlesummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_title', models.TextField(help_text='De venstertitel waarop gegroepeerd is.')),
                ('total_seconds', models.PositiveIntegerField(help_text='Cumulatieve actieve tijd voor deze titel binnen het blok.')),
            ],
            options={
                'verbose_name': 'unieke activiteit',
                'verbose_name_plural': 'unieke activiteiten',
                'ordering': ['-total_seconds'],
            },
        ),
        migrations.RemoveField(
            model_name='activityblock',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='activityblock',
            name='dominant_title',
        ),
        migrations.AlterField(
            model_name='activityblock',
            name='activity_count',
            field=models.PositiveIntegerField(help_text='Aantal WindowActivity-regels samengevoegd in dit blok.'),
        ),
        migrations.AlterField(
            model_name='activityblock',
            name='total_seconds',
            field=models.PositiveIntegerField(help_text='Opgetelde actieve seconden van alle onderliggende WindowActivity-regels.'),
        ),
        migrations.DeleteModel(
            name='BlockTitleSummary',
        ),
        migrations.AddField(
            model_name='uniqueactivity',
            name='block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unique_activities', to='activities.activityblock'),
        ),
        migrations.AddField(
            model_name='uniqueactivity',
            name='occurrences',
            field=models.ManyToManyField(help_text='De individuele WindowActivity-regels met deze titel.', related_name='unique_activities', to='activities.windowactivity'),
        ),
    ]
