# Generated by Django 4.2.29 on 2026-03-31 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_uniqueactivity_remove_activityblock_activities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniqueactivity',
            name='occurrences',
        ),
        migrations.AddField(
            model_name='windowactivity',
            name='unique_activity',
            field=models.ForeignKey(blank=True, help_text='De UniqueActivity waar deze regel na aggregatie toe behoort.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='activities.uniqueactivity'),
        ),
    ]
