# Generated by Django 4.2.29 on 2026-06-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockprojecthistory',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Het project waartoe het block is toegewezen. Null = handmatig ontkoppeld.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='block_assignments', to='projects.project'),
        ),
    ]
