# Generated by Django 4.2.29 on 2026-06-28 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_blockprojecthistory_project_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityblock',
            name='comment',
            field=models.TextField(blank=True, default='', help_text='Optionele notitie of toelichting bij dit blok (bijv. taakomschrijving).'),
        ),
    ]
